### ISSUE TITLE
Add a "Usage" section in the ReadMe.md

### ISSUE THREAD

**Issue by ikluhsman** [MattSchaeffer/EventFiend#4]
Add a "Usage" section in the readme.md in the repository to let end-users of the app know how to run this application. Personally I would like to be able to run the app using a command line as well as using the GUI where both provide the same functionality.

**Comment by ikluhsman** [comment]
May also output usage if improper arguments are passed to the script as well.

**Comment by MattSchaeffer** [comment]
Task completed
